baseURL = "https://www.haydensmith.com/"
title = "Shell"
# author = "Yukuro"
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[Params]

# Additions start here
  [Params.Navbar]
  use = true
  
  [Params.Extensions]
  use = true
  ext = ".txt" # extension to add after single page
# Additions stop here
    
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "Tasha Pais's Portfolio!"
  [Params.Terminal]
  # Note: color scheme
  # Note: You can choose between
  # Note: hugo-theme-shell original: ["shell-powershell", "shell-ubuntu", "shell-retro"]
  # Note: gogh theme: https://mayccoll.github.io/Gogh/
  scheme = "Molokai"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "Hayden"
  pcName = "myPortal"
  workDir = "mydir"
  profile = "profile.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # terminalDelay = 20 : deprecated

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  # activityDelay = 5 : deprecated

  description = """
Hi I am Hayden Smith! 

I am an asipring <span style="color:orchid">Software Engineer.</span> 
I can also hoop a little and run a pretty fast mile.

I grew up in Burleson, Texas and completed my undergraduate degree from <span style="color:crimson">University of Oklahoma.</span> 
Currently looking for a <span style="color:mediumvioletred">web development or cloud engineering</span> position.

One of my biggest interests is diving deep into new tech
and <span style="color:darkblue">building technical competence.</span>

Check out my <a href="https://www.notion.so/Hayden-s-Ledger-e84457929af1418681f90172d5bf1e27">ledger</a> and <a href="https://github.com/HaydenSmith25">code</a>. Connect with me on <a href="https://twitter.com/htimsnedyah">Twitter</a> or <a href="https://www.linkedin.com/in/smith-hayden/">LinkedIn</a>.


  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "my_activity"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
["NBA API to get player stats from any season.", "https://github.com/HaydenSmith25/NBA-API"],
  ["My latest fully functioning Solana application", "https://solana-game.vercel.app/"],
  ["An upcoming workshop about my contrarian take on web3", "https://csc.barnard.edu/events/postponed-pop-workshop-web3-and-new-world-order-blockchain-first-principles-developer"],
  ["Playlist of past piano performances I'm adding to", "https://www.youtube.com/playlist?list=PL3rUNYN0nAwpCO2Xk6KlmptSmprpcpId6"],
  ["Assorted ideas I frequently think of", "/thoughts.md"],
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
